[package]
name = "stack"
edition = "2024"
version.workspace = true
publish = false


[dependencies]
tokio.workspace = true
rsweb-app.workspace = true
warp.workspace = true
dotenvy.workspace = true
rsweb-api.workspace = true
